# TCL File Generated by Component Editor 15.1
# Tue Jul 19 17:03:47 PDT 2016
# DO NOT MODIFY


# 
# read_pipeline "read_pipeline" v1.0
#  2016.07.19.17:03:47
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module read_pipeline
# 
set_module_property DESCRIPTION ""
set_module_property NAME read_pipeline
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME read_pipeline
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL read_pipeline
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file read_pipeline.vhd VHDL PATH test_components/read_pipeline.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL read_pipeline
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file read_pipeline.vhd VHDL PATH test_components/read_pipeline.vhd


# 
# parameters
# 
add_parameter REGISTER_SIZE INTEGER 32
set_parameter_property REGISTER_SIZE DEFAULT_VALUE 32
set_parameter_property REGISTER_SIZE DISPLAY_NAME REGISTER_SIZE
set_parameter_property REGISTER_SIZE TYPE INTEGER
set_parameter_property REGISTER_SIZE UNITS None
set_parameter_property REGISTER_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property REGISTER_SIZE HDL_PARAMETER true
add_parameter MAX_PIPELINE INTEGER 7
set_parameter_property MAX_PIPELINE DEFAULT_VALUE 7
set_parameter_property MAX_PIPELINE DISPLAY_NAME MAX_PIPELINE
set_parameter_property MAX_PIPELINE TYPE INTEGER
set_parameter_property MAX_PIPELINE UNITS None
set_parameter_property MAX_PIPELINE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MAX_PIPELINE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end pipeline_count name Input 3


# 
# connection point master_in
# 
add_interface master_in avalon end
set_interface_property master_in addressUnits SYMBOLS
set_interface_property master_in associatedClock clock
set_interface_property master_in associatedReset reset
set_interface_property master_in bitsPerSymbol 8
set_interface_property master_in burstOnBurstBoundariesOnly false
set_interface_property master_in burstcountUnits WORDS
set_interface_property master_in explicitAddressSpan 0
set_interface_property master_in holdTime 0
set_interface_property master_in linewrapBursts false
set_interface_property master_in maximumPendingReadTransactions 1
set_interface_property master_in maximumPendingWriteTransactions 0
set_interface_property master_in readLatency 0
set_interface_property master_in readWaitTime 1
set_interface_property master_in setupTime 0
set_interface_property master_in timingUnits Cycles
set_interface_property master_in writeWaitTime 0
set_interface_property master_in ENABLED true
set_interface_property master_in EXPORT_OF ""
set_interface_property master_in PORT_NAME_MAP ""
set_interface_property master_in CMSIS_SVD_VARIABLES ""
set_interface_property master_in SVD_ADDRESS_GROUP ""

add_interface_port master_in m_address address Input 8
add_interface_port master_in m_byteenable byteenable Input register_size/8
add_interface_port master_in m_read read Input 1
add_interface_port master_in m_readdata readdata Output register_size
add_interface_port master_in m_response response Output 2
add_interface_port master_in m_write write Input 1
add_interface_port master_in m_writedata writedata Input register_size
add_interface_port master_in m_lock lock Input 1
add_interface_port master_in m_waitrequest waitrequest Output 1
add_interface_port master_in m_readdatavalid readdatavalid Output 1
set_interface_assignment master_in embeddedsw.configuration.isFlash 0
set_interface_assignment master_in embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment master_in embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment master_in embeddedsw.configuration.isPrintableDevice 0


# 
# connection point slave_out
# 
add_interface slave_out avalon start
set_interface_property slave_out addressUnits SYMBOLS
set_interface_property slave_out associatedClock clock
set_interface_property slave_out associatedReset reset
set_interface_property slave_out bitsPerSymbol 8
set_interface_property slave_out burstOnBurstBoundariesOnly false
set_interface_property slave_out burstcountUnits WORDS
set_interface_property slave_out doStreamReads false
set_interface_property slave_out doStreamWrites false
set_interface_property slave_out holdTime 0
set_interface_property slave_out linewrapBursts false
set_interface_property slave_out maximumPendingReadTransactions 1
set_interface_property slave_out maximumPendingWriteTransactions 0
set_interface_property slave_out readLatency 0
set_interface_property slave_out readWaitTime 1
set_interface_property slave_out setupTime 0
set_interface_property slave_out timingUnits Cycles
set_interface_property slave_out writeWaitTime 0
set_interface_property slave_out ENABLED true
set_interface_property slave_out EXPORT_OF ""
set_interface_property slave_out PORT_NAME_MAP ""
set_interface_property slave_out CMSIS_SVD_VARIABLES ""
set_interface_property slave_out SVD_ADDRESS_GROUP ""

add_interface_port slave_out s_address address Output 8
add_interface_port slave_out s_byteenable byteenable Output register_size/8
add_interface_port slave_out s_read read Output 1
add_interface_port slave_out s_readdata readdata Input register_size
add_interface_port slave_out s_response response Input 2
add_interface_port slave_out s_write write Output 1
add_interface_port slave_out s_writedata writedata Output register_size
add_interface_port slave_out s_lock lock Output 1
add_interface_port slave_out s_waitrequest waitrequest Input 1
add_interface_port slave_out s_readdatavalid readdatavalid Input 1

