# TCL File Generated by Component Editor 15.1
# Thu Dec 14 12:45:46 PST 2017
# DO NOT MODIFY


#
# Lightweight_Vector_Extensions "Lightweight_Vector_Extensions" v1.0
#  2017.12.14.12:45:46
#
#

#
# request TCL package from ACDS 15.1
#
package require -exact qsys 15.1

proc log2 { num } {
    set retval 0
    while { $num > 1 } {
        set retval [expr $retval + 1 ]
        set num [expr $num / 2 ]
    }
    return $retval
}


#
# module Lightweight_Vector_Extensions
#
set_module_property DESCRIPTION ""
set_module_property NAME lve
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "VectorBlox Computing Inc."
set_module_property GROUP  "VectorBlox Computing Inc."
set_module_property DISPLAY_NAME "Lightweight Vector Extensions"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


#
# file sets
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL lve_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false

add_fileset_file vblox_lve/utils.vhd VHDL PATH ../orca/hdl/utils.vhd
add_fileset_file vblox_lve/constants_pkg.vhd VHDL PATH ../orca/hdl/constants_pkg.vhd
add_fileset_file vblox_lve/lve_components.vhd VHDL PATH hdl/lve_components.vhd
add_fileset_file vblox_lve/lve_core.vhd VHDL PATH hdl/lve_core.vhd
add_fileset_file vblox_lve/lve.vhd VHDL PATH hdl/lve.vhd
add_fileset_file vblox_lve/4port_mem.vhd VHDL PATH hdl/4port_mem.vhd
add_fileset_file vblox_lve/lve_ci.vhd VHDL PATH hdl/lve_ci.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL lve_top
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vblox_lve/utils.vhd VHDL PATH ../orca/hdl/utils.vhd
add_fileset_file vblox_lve/constants_pkg.vhd VHDL PATH ../orca/hdl/constants_pkg.vhd
add_fileset_file vblox_lve/lve_components.vhd VHDL PATH hdl/lve_components.vhd
add_fileset_file vblox_lve/lve_core.vhd VHDL PATH hdl/lve_core.vhd
add_fileset_file vblox_lve/lve.vhd VHDL PATH hdl/lve.vhd
add_fileset_file vblox_lve/4port_mem.vhd VHDL PATH hdl/4port_mem.vhd
add_fileset_file vblox_lve/lve_ci.vhd VHDL PATH hdl/lve_ci.vhd

set width 32

#
# parameters
#

add_parameter POWER_OPTIMIZED INTEGER 0
set_parameter_property POWER_OPTIMIZED DEFAULT_VALUE 0
set_parameter_property POWER_OPTIMIZED DISPLAY_NAME POWER_OPTIMIZED
set_parameter_property POWER_OPTIMIZED TYPE INTEGER
set_parameter_property POWER_OPTIMIZED UNITS None
set_parameter_property POWER_OPTIMIZED HDL_PARAMETER true
add_parameter SCRATCHPAD_ADDR_BITS INTEGER 16
set_parameter_property SCRATCHPAD_ADDR_BITS DISPLAY_NAME SCRATCHPAD_ADDR_BITS
set_parameter_property SCRATCHPAD_ADDR_BITS TYPE INTEGER
set_parameter_property SCRATCHPAD_ADDR_BITS UNITS None
set_parameter_property SCRATCHPAD_ADDR_BITS HDL_PARAMETER true

add_parameter AXI_ENABLE INTEGER 1
set_parameter_property AXI_ENABLE HDL_PARAMETER true
set_parameter_property AXI_ENABLE VISIBLE false

add_parameter WISHBONE_ENABLE INTEGER 0
set_parameter_property WISHBONE_ENABLE HDL_PARAMETER true
set_parameter_property WISHBONE_ENABLE VISIBLE false


#
# display items
#


#
# connection point clock
#
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1

add_interface clk_2x clock end
set_interface_property clk_2x clockRate 0
set_interface_property clk_2x ENABLED true
set_interface_property clk_2x EXPORT_OF ""
set_interface_property clk_2x PORT_NAME_MAP ""
set_interface_property clk_2x CMSIS_SVD_VARIABLES ""
set_interface_property clk_2x SVD_ADDRESS_GROUP ""

add_interface_port clk_2x scratchpad_clk clk Input 1


#
# connection point reset
#
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


#
# connection point conduit_end
#
add_interface vcp conduit end
set_interface_property vcp associatedClock clock
set_interface_property vcp associatedReset reset
set_interface_property vcp ENABLED true

add_interface_port vcp vcp_data0            data0             Input  $width
add_interface_port vcp vcp_data1            data1             Input  $width
add_interface_port vcp vcp_data2            data2             Input  $width
add_interface_port vcp vcp_instruction      instruction       Input  41
add_interface_port vcp vcp_valid_instr      valid_instr       Input  1
add_interface_port vcp vcp_ready            ready             Output 1
add_interface_port vcp vcp_writeback_data   writeback_data    Output 32
add_interface_port vcp vcp_writeback_en     writeback_en      Output 1
add_interface_port vcp vcp_alu_data1        alu_data1         Output $width
add_interface_port vcp vcp_alu_data2        alu_data2         Output $width
add_interface_port vcp vcp_alu_used         alu_used          Output 1
add_interface_port vcp vcp_alu_source_valid alu_source_valid  Output 1
add_interface_port vcp vcp_alu_result       alu_result        Input  $width
add_interface_port vcp vcp_alu_result_valid alu_result_valid  Input  1

add_interface wb conduit end
set_interface_property wb associatedClock clock
set_interface_property wb associatedReset reset
set_interface_property wb ENABLED false

add_interface_port wb slave_ADR_I   ADR_I   Input  SCRATCHPAD_ADDR_BITS
add_interface_port wb slave_DAT_O   DAT_O   Output $width
add_interface_port wb slave_DAT_I   DAT_I   Input  $width
add_interface_port wb slave_WE_I    WE_I    Input  1
add_interface_port wb slave_SEL_I   SEL_I   Input  $width/8
add_interface_port wb slave_STB_I   STB_I   Input  1
add_interface_port wb slave_ACK_O   ACK_O   Output 1
add_interface_port wb slave_CYC_I   CYC_I   Input  1
add_interface_port wb slave_CTI_I   CTI_I   Input  3
add_interface_port wb slave_STALL_O	STALL_O Output 1


add_interface axi_slave axi end
set_interface_property axi_slave associatedClock clock
set_interface_property axi_slave associatedReset reset
set_interface_property axi_slave readAcceptanceCapability 1
set_interface_property axi_slave writeAcceptanceCapability 4
set_interface_property axi_slave combinedAcceptanceCapability 4
set_interface_property axi_slave ENABLED true
set_interface_property axi_slave EXPORT_OF ""
set_interface_property axi_slave PORT_NAME_MAP ""
set_interface_property axi_slave CMSIS_SVD_VARIABLES ""
set_interface_property axi_slave SVD_ADDRESS_GROUP ""

add_interface_port axi_slave slave_ARADDR  araddr  Input SCRATCHPAD_ADDR_BITS
add_interface_port axi_slave slave_ARBURST arburst Input 2
add_interface_port axi_slave slave_ARCACHE arcache Input 4
add_interface_port axi_slave slave_ARID    arid    Input 4
add_interface_port axi_slave slave_ARLEN   arlen   Input 4
add_interface_port axi_slave slave_ARLOCK  arlock  Input 2
add_interface_port axi_slave slave_ARPROT  arprot  Input 3
add_interface_port axi_slave slave_ARREADY arready Output 1
add_interface_port axi_slave slave_ARSIZE  arsize  Input 3
add_interface_port axi_slave slave_ARVALID arvalid Input 1
add_interface_port axi_slave slave_AWADDR  awaddr  Input SCRATCHPAD_ADDR_BITS
add_interface_port axi_slave slave_AWBURST awburst Input 2
add_interface_port axi_slave slave_AWCACHE awcache Input 4
add_interface_port axi_slave slave_AWID    awid    Input 4
add_interface_port axi_slave slave_AWLEN   awlen   Input 4
add_interface_port axi_slave slave_AWLOCK  awlock  Input 2
add_interface_port axi_slave slave_AWPROT  awprot  Input 3
add_interface_port axi_slave slave_AWREADY awready Output 1
add_interface_port axi_slave slave_AWSIZE  awsize  Input 3
add_interface_port axi_slave slave_AWVALID awvalid Input 1
add_interface_port axi_slave slave_BID     bid     Output 4
add_interface_port axi_slave slave_BREADY  bready  Input 1
add_interface_port axi_slave slave_BRESP   bresp   Output 2
add_interface_port axi_slave slave_BVALID  bvalid  Output 1
add_interface_port axi_slave slave_RDATA   rdata   Output $width
add_interface_port axi_slave slave_RID     rid     Output 4
add_interface_port axi_slave slave_RLAST   rlast   Output 1
add_interface_port axi_slave slave_RREADY  rready  Input 1
add_interface_port axi_slave slave_RRESP   rresp   Output 2
add_interface_port axi_slave slave_RVALID  rvalid  Output 1
add_interface_port axi_slave slave_WDATA   wdata   Input $width
add_interface_port axi_slave slave_WID     wid     Input 4
add_interface_port axi_slave slave_WLAST   wlast   Input 1
add_interface_port axi_slave slave_WREADY  wready  Output 1
add_interface_port axi_slave slave_WSTRB   wstrb   Input $width/8
add_interface_port axi_slave slave_WVALID  wvalid  Input 1
