#Config for testing balanced cached system
BD_EXTENSION=_cached
EXTRA_CFLAGS=-mno-div
export EXTRA_CFLAGS

MAX_IFETCHES_IN_FLIGHT=1
BTB_ENTRIES=16
MULTIPLY_ENABLE=1
DIVIDE_ENABLE=0
#SHIFTER_MAX_CYCLES=32
ENABLE_EXCEPTIONS=1
PIPELINE_STAGES=4
#ENABLE_EXT_INTERRUPTS=0
ICACHE_SIZE=8192
INSTRUCTION_REQUEST_REGISTER=0
INSTRUCTION_RETURN_REGISTER=0
IUC_REQUEST_REGISTER=2
IUC_RETURN_REGISTER=0
IAUX_REQUEST_REGISTER=2
IAUX_RETURN_REGISTER=0
IC_REQUEST_REGISTER=0
IC_RETURN_REGISTER=0
DCACHE_SIZE=8192
DCACHE_WRITEBACK=1
DATA_REQUEST_REGISTER=1
DATA_RETURN_REGISTER=0
DUC_REQUEST_REGISTER=2
DUC_RETURN_REGISTER=0
DAUX_REQUEST_REGISTER=2
DAUX_RETURN_REGISTER=0
DC_REQUEST_REGISTER=1
DC_RETURN_REGISTER=0
