#Config for testing minimum-size TCM system
BD_EXTENSION=_tcm
ARCH=rv32i
export ARCH

MAX_IFETCHES_IN_FLIGHT=1
BTB_ENTRIES=0
MULTIPLY_ENABLE=0
DIVIDE_ENABLE=0
SHIFTER_MAX_CYCLES=32
ENABLE_EXCEPTIONS=0
PIPELINE_STAGES=4
ENABLE_EXT_INTERRUPTS=0
ICACHE_SIZE=0
INSTRUCTION_REQUEST_REGISTER=0
INSTRUCTION_RETURN_REGISTER=0
IUC_REQUEST_REGISTER=0
IUC_RETURN_REGISTER=0
IAUX_REQUEST_REGISTER=0
IAUX_RETURN_REGISTER=0
IC_REQUEST_REGISTER=0
IC_RETURN_REGISTER=0
DCACHE_SIZE=0
DCACHE_WRITEBACK=0
DATA_REQUEST_REGISTER=0
DATA_RETURN_REGISTER=0
DUC_REQUEST_REGISTER=0
DUC_RETURN_REGISTER=0
DAUX_REQUEST_REGISTER=0
DAUX_RETURN_REGISTER=0
DC_REQUEST_REGISTER=0
DC_RETURN_REGISTER=0
